local M = {
  lsp = {
    "lua_ls",
    "ts_ls",
    "html",
    "cssls",
    "tailwindcss",
    "rust_analyzer",
    "rescriptls",
    "jsonls",
    "eslint",
    "emmet_language_server",
  },
  mason = {
    "css-lsp",
    "html-lsp",
    "eslint-lsp",
    "vue-language-server",
    "lua-language-server",
    "typescript-language-server",
    "tailwindcss-language-server",
    "rescript-language-server",
    "stylua",
    "deno",
    "prettier",
    "eslint_d",
    "rust-analyzer",
    "json-lsp",
    "emmet-language-server",
  },
  treesitter = {
    "bash",
    "vim",
    "lua",
    "vimdoc",
    "html",
    "css",
    "javascript",
    "typescript",
    "tsx",
    "markdown",
    "markdown_inline",
    "rust",
    "json",
    "http",
  },
}

return M
