local M = {
  lsp = {
    "lua_ls",
    "ts_ls",
    "html",
    "cssls",
    "tailwindcss",
    "rust_analyzer",
    "rescriptls",
    "gdscript",
    "nil_ls",
  },
  mason = {
    "css-lsp",
    "html-lsp",
    "eslint-lsp",
    "vue-language-server",
    "lua-language-server",
    "typescript-language-server",
    "tailwindcss-language-server",
    "rescript-language-server",
    "stylua",
    "deno",
    "prettier",
    "rust-analyzer",
    "gdtoolkit",
    "nil",
  },
  treesitter = {
    "gdscript",
    "godot_resource",
    "gdshader",
    "bash",
    "vim",
    "lua",
    "vimdoc",
    "html",
    "css",
    "javascript",
    "typescript",
    "tsx",
    "markdown",
    "markdown_inline",
    "rust",
  },
}

return M
